version: '3.0'
services:

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        expose:
            - "2181"
        container_name: zookeeper

    kafka:
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_CREATE_TOPICS: "input-twitter:1:1, output-twitter:1:1"
            KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            container_name: kafka

    consumer:
        image: streams-consumer
        ports: 
            - "8082:8082"
        expose:
            - "8082"
        environment:
            container_name: consumer
            
    producer:
        image: streams-producer
        ports: 
            - "8080:8080"
        expose:
            - "8080"
        environment:
            container_name: producer
    
    stream:
        image: streams-kstream
        ports: 
            - "8081:8081"
        expose:
            - "8081"
        environment:
            container_name: stream
        
            
    

        